# -*- coding: utf-8 -*-
"""PKL_file

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ywudt05cKS-1qcpwLEOuLPaFuEbBuYTN
"""

import urllib.request

url = "https://example.com/your_file.pkl"
destination = "phishing_url_detector.pkl"